# Generated by Django 4.2.2 on 2023-08-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='korz',
            field=models.ImageField(default='public/public/img/10354898_cart_trolley_ui_web_icon.svg', upload_to=''),
        ),
        migrations.AddField(
            model_name='item',
            name='ptich',
            field=models.ImageField(default='public/public/img/326572_check_icon.svg', upload_to=''),
        ),
    ]
