# Generated by Django 4.2.2 on 2023-09-02 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_item_korz_alter_item_ptich'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='item',
            name='korz',
            field=models.CharField(default='10354898_cart_trolley_ui_web_icon.svg', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='ptich',
            field=models.CharField(default='326572_check_icon.svg', max_length=200),
        ),
    ]
