# Generated by Django 4.2.2 on 2023-09-02 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_order_data_alter_item_korz_alter_item_ptich'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
